s = input().split()
s[0] = int(s[0])
s[1] = int(s[1])
s[2] = int(s[2])
print((s[0] + s[1]) % s[2])
print(((s[0] % s[2]) + (s[1] % s[2])) % s[2])
print((s[0] * s[1]) % s[2])
print(((s[0] % s[2]) * (s[1] % s[2])) % s[2])
